services:
  ansible:
    dns:
      - 192.168.1.1 # Internal DNS
      - 8.8.8.8 # fallback
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
      #  Pip Cache
      - ansible-pip-cache:/root/.cache/pip
      #  Ansible Collection Cache
      - ansible-collections:/root/.ansible
    command: sleep infinity
    network_mode: host
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
      - ANSIBLE_RETRY_FILES_ENABLED=False
      - ANSIBLE_STDOUT_CALLBACK=default
      - ANSIBLE_RESULT_FORMAT=yaml

volumes:
  ansible-pip-cache:
  ansible-collections:
